server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/flyway?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&rewriteBatchedStatements=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456

  flyway:
    enabled: true
    clean-disabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations:
      - classpath:db/migration
