spring:
  mail:
    host: smtp.163.com
    port: 465
    protocol: smtp
    default-encoding: UTF-8
    username: 15217742393@163.com
    password: TMLGXVEIRCFHZNFG
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
server:
  port: 8088
